#!/usr/bin/python

import sys
import codecs

f = codecs.open(sys.argv[1], 'r', sys.argv[2])
u = f.read()   # now the contents have been transformed to a Unicode string
out = codecs.open(sys.argv[3], 'w', 'utf-8')
out.write(u)   # and now the contents have been output as UTF-8

