<?php
header("Content-type:text/plain; charset=UTF-8");
/*
 * This PHP script is generated by CLARIN-DK's tool registration form 
 * (http://localhost/texton/register). It should, with no or few adaptations
 * work out of the box as a dummy for your web service. The output returned
 * to the CLARIN-DK workflow manager is just a listing of the HTTP parameters
 * received by this web service from the CLARIN-DK workflow manager, and not
 * the output proper. For that you have to add your code to this script and
 * deactivate the dummy functionality. (The comments near the end of this
 * script explain how that is done.)
 *
 * Places in this script that require your attention are marked 'TODO'.
 */
/*
ToolID         : CST-Lem
PassWord       : 
Version        : 5.06.2014.0809
Title          : CSTlemma
Path in URL    : CST-lemma/	*** TODO make sure your web service listens on this path and that this script is readable for the webserver. ***
Publisher      : CST
ContentProvider: cst.ku.dk
Creator        : CST
InfoAbout      : cst.dk
Description    : Produces the dictionary look-up form (or lemma) for each word, inflected or not, in the input.
ExternalURI    : https://nlpweb01.nors.ku.dk/tools/
XMLparms       : 
PostData       : 
Inactive       : 
*/

/*******************
* helper functions *
*******************/
$toollog = '../log/CSTLem.log'; /* Used by the logit() function. TODO make sure the folder exists and is writable. Adapt if needed */
                
/*  TODO Set $dodelete to false if temporary files in /tmp should not be deleted before returning. */
$dodelete = true;
$tobedeleted = array();


function loginit()  /* Wipes the contents of the log file! TODO Change this behaviour if needed. */
    {
    return;
    global $toollog,$ftemp;
    $ftemp = fopen($toollog,'w');
    if($ftemp)
        {
        fwrite($ftemp,$toollog . "\n");
        fclose($ftemp);
        }
    }
    
function logit($str) /* TODO You can use this function to write strings to the log file. */
    {
    return;
    global $toollog,$ftemp;
    $ftemp = fopen($toollog,'a');
    if($ftemp)
        {
        fwrite($ftemp,$str . "\n");
        fclose($ftemp);
        }
    }
    
class SystemExit extends Exception {}
try {
    function hasArgument ($parameterName)
        {
        return isset($_REQUEST["$parameterName"]);
        }

    function getArgument ($parameterName)
        {
        return isset($_REQUEST["$parameterName"]) ? $_REQUEST["$parameterName"] : "";
        }

    function existsArgumentWithValue ($parameterName, $parameterValue)
        {
        /* Check whether there is an argument <parameterName> that has value 
           <parameterValue>. 
           There may be any number of arguments with name <parameterName> !
        */
        $query  = explode('&', $_SERVER['QUERY_STRING']);

        foreach( $query as $param )
            {
            list($name, $value) = explode('=', $param);
            if($parameterName == urldecode($name) && $parameterValue == urldecode($value))
                return true;
            }
        return false;
        }

    function tempFileName($suff) /* TODO Use this to create temporary files, if needed. */
        {
        global $dodelete;
        global $tobedeleted;
        $tmpno = tempnam('/tmp', $suff);
        if($dodelete)
            $tobedeleted[$tmpno] = true;
        return $tmpno;
        }
        
    function requestFile($requestParm) // e.g. "IfacettokF"
        {
        logit("requestFile({$requestParm})");

        if(isset($_REQUEST[$requestParm]))
            {
            $urlbase = isset($_REQUEST["base"]) ? $_REQUEST["base"] : "http://localhost/toolsdata/";

            $item = $_REQUEST[$requestParm];
            $url = $urlbase . urlencode($item);
            logit("requestParm:$requestParm");
            logit("urlbase:$urlbase");
            logit("item:$item");
            logit("url[$url]");

            $handle = fopen($url, "r");
            if($handle == false)
                {
                logit("Cannot open url[$url]");
                return "";
                }
            else
                {
                $tempfilename = tempFileName("CSTLem_{$requestParm}_");
                $temp_fh = fopen($tempfilename, 'w');
                if($temp_fh == false)
                    {
                    fclose($handle);
                    logit("handle closed. Cannot open $tempfilename");
                    return "";
                    }
                else
                    {
                    while (!feof($handle)) 
                        {
                        $read = fread($handle, 8192);
                        fwrite($temp_fh, $read);    
                        }
                    fclose($temp_fh);
                    fclose($handle);
                    return $tempfilename;
                    }
                }
            }
        logit("empty");
        return "";
        }    

    function splits($toolbin,$filename,$attribute,$annotation,$idprefix,$ancestor,$element)
        {
        $lemfile = tempFileName("split-".$attribute);
        $command = "python3 ../shared_scripts/pysplit.py $filename $lemfile $ancestor $element $attribute $annotation $idprefix Slem";

        logit($command);

        if(($cmd = popen($command, "r")) == NULL)
            {
            throw new SystemExit(); // instead of exit()
            }

        while($read = fgets($cmd))
            {
            }
        return $lemfile;
        }

function lemmatiser($Oformatflat,$Ofacetlem,$Ofacetpos,$Ofacetseg,$Ofacettok,$ShowTag, $Ipresnml, $Opresalf,$Opresfrq,$Opresnml, $Oambiguna, $Iappnrm,$element,$ancestor,$toolres,$toolbin,$language,$toptarg,$foptarg,$filename,$pos,$posattribute,$emptyattribute,$XMLinput,$Iperiodc13,$Iperiodc20)
    {
    $tmpno = tempFileName("lemma-results");
    $dict = "/dict";
    $periodsubdir = "";
    $Uminus = "-";
    $H = "1";
    //$c = "\$b1[[\$b~1]?\$B]";
    //$c = "\$b[[\$b0]?(\$B)]";
    $cx = "\$b1[[\$b?]~1\$B]";
    if($Oformatflat)
        $sep = " -s'|' ";
    else
        $sep = " -s'\\011' ";
    $i = false;

    $wt = "\$w\\t";
    
    /*  $Ofacetlem
        $Ofacetsl
        $Ofacetstl
        $Ofacetstlp
        $Ofacettl
        $Ofacettlp
    */

    /* $Ofacetlem || $Ofacetsl */
    if($Ofacetlem && !$Ofacetpos && !$Ofacettok)
        $wt = ""; 

    $eind = "\$s\\n";
    /* $Ofacetlem || $Ofacettl || $Ofacettlp */
    if($Ofacetlem && !$Ofacetseg) 
        $eind = "\\n";

    if($i)
        {
        if($Opresnml && !$ShowTag)
            $c = "$wt\$b[[\$b?]0\$B]\\t\$i$eind";
        else if($toptarg == '-')
            $c = "$wt\$b[[\$b?]0\$B]\\t\$i$eind";
        else
          //$c = "$wt\$t\\t\$b[[\$b?]0\$B]\\t\$i$eind"; // word tag lemma info
            $c = "$wt\$b[[\$b?]0\$B]\\t\$t\\t\$i$eind"; // word lemma tag info
        }
    else
        {
        if($Opresnml && !$ShowTag)
            $c = "$wt\$b[[\$b?]0\$B]$eind";
        else if($toptarg == '-')
            $c = "$wt\$b[[\$b?]0\$B]$eind";
        else
          //$c = "$wt\$t\\t\$b[[\$b?]0\$B]$eind"; // word tag lemma
            $c = "$wt\$b[[\$b?]0\$B]\\t\$t$eind"; // word lemma tag
        }

    logit("c=" . $c);

    $x = "";
    $flexrules = "flexrules";
    
    if($language == 'af')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'bg')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'cs')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'da')
        {
        if($Iperiodc20)
            {
            if($Iappnrm)
                {
                $periodsubdir = "/c20n";
                $flexrules = "flexrules.ods_170412.csv.corrected-lems.txt.ph_12_XC";
                if($pos == 'n')
                    $flexrulessubdir = "/1";
                else
                    {
                    $flexrules = "flexrules";
                    $flexrulessubdir = "/links";
                    $x = "-x'$toolres/da/lemmatiser/tags/c20n/translationTable'";
                    }
                }
            else
                {
                $periodsubdir = "/c19n";
                $flexrules = "flexrules.ods_170412.csv.corrected.ph_12_XC";
                if($pos == 'n')
                    $flexrulessubdir = "/1";
                else
                    {
                    $flexrules = "flexrules";
                    $flexrulessubdir = "/links";
                    $x = "-x'$toolres/da/lemmatiser/tags/c19n/translationTable'";
                    }
                } 
            }
        else if($Iperiodc13)
            {
            $periodsubdir = "/c13-c18";
            if($pos == 'n')
                $flexrulessubdir = "/1";
            else // Not the case, currently (May 2018)
                {
                $flexrulessubdir = "/links";
                $x = "-x'$toolres/da/lemmatiser/tags/c13-c18/translationTable'";
                }
            }
        else
            {
            $periodsubdir = "/c21";
            if($pos == 'n')
                $flexrulessubdir = "/1";
            else
		{
                $flexrulessubdir = "/links";
		$x = "-x'$toolres/da/lemmatiser/tags/c21/translationTable'";
	        }
            }
        }
    else if($language == 'de')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'el')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'en')
        {
	if($pos=='n')
            $flexrulessubdir = "/2";
	else
            $flexrulessubdir = "/links";
        $flexrules = "flexrules";
        if($toptarg == '')
            $x = "-x'$toolres/en/lemmatiser/tags/translation'";
        }
    else if($language == 'es')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'et')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'fa')
        {
        $flexrulessubdir = "/3";
        }
    else if($language == 'fr')
        {
        $flexrulessubdir = "/1";
        $flexrules = "flexrules.frlexambi.uden.dubletter.ph_XC";
        }
    else if($language == 'hr')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'hu')
        {
        $flexrulessubdir = "/0";
        }
    else if($language == 'is')
        {
        $flexrules = "icelandic.flexrules";
        }
    else if($language == 'it')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'la')
        {
        $flexrulessubdir = "/2";
        }
    else if($language == 'mk')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'nl')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'no')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'pl')
        {
        $flexrulessubdir = "/0";
        $flexrules = "flexrules.polimorfologik.txt.ph_ziggurat_XC";
        }
    else if($language == 'pt')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'ro')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'ru')
        {
        $flexrulessubdir = "/1";
	$flexrules = "flexrules.ru-lemma.tabru-msd-ru-lemma-cleaned.ph_XC";
        }
    else if($language == 'sk')
        {
        $flexrulessubdir = "/0";
        }
    else if($language == 'sl')
        {
        $flexrulessubdir = "/0";
        }
    else if($language == 'sr')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'sv')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'tr')
        {
        $flexrulessubdir = "/1";
        }
    else if($language == 'uk')
        {
        $flexrulessubdir = "";
        }
    else
        {
        $flexrulessubdir = "";
        }
   
    if($toptarg == '')
	// input is tagged
        {
        $Iflat = ''; // Important! '$w/$t\\s' does not find last occurrence of slash
		// Default is that slash separates word from tag. This uses different code.
        }
    else
        // input is not tagged
        {
        $Iflat = "-I'\$w\\s'";
        }
    logit("language $language");
    if($Oambiguna)
        {
        $Uminus = "";
        $uminus = "";
        $H = "0";
        logit("Uminus $Uminus");
        } 

    if($Ipresnml && !$Opresnml || $ShowTag) 
        {
        logit("Not normal!");
        if($Opresalf)
            if($Ofacetlem)
                $command = "$toolbin/cstlemma -L $Iflat -eU -p -qwft -t$toptarg -U$Uminus -u$Uminus -H$H -B'\$f\\t\$w\\n' -b'\$f\\t\$w\\n' -l- -f'$toolres/$language/lemmatiser/$foptarg$periodsubdir$flexrulessubdir/$flexrules' -d'$toolres/$language/lemmatiser/$foptarg$periodsubdir$dict' -i $filename -o $tmpno";
            else if($ShowTag)
                $command = "$toolbin/cstlemma -L $Iflat -eU -p -qwft -t$toptarg -U$Uminus -u$Uminus -H$H -B'\$f\\t\$w\\t\$W\\n' -b'\$f\\t\$w\\t\$W\\n' -W'\$f\\t\$w\\t\$t' -l- -f'$toolres/$language/lemmatiser/$foptarg$periodsubdir$flexrulessubdir/$flexrules' -d'$toolres/$language/lemmatiser/$foptarg$periodsubdir$dict' -i $filename -o $tmpno";
            else
                $command = "$toolbin/cstlemma -L $Iflat -eU -p -qwft -t$toptarg -U$Uminus -u$Uminus -H$H -B'\$f\\t\$w\\t\$W\\n' -b'\$f\\t\$w\\t\$W\\n' -W'\$f\\t\$w' -l- -f'$toolres/$language/lemmatiser/$foptarg$periodsubdir$flexrulessubdir/$flexrules' -d'$toolres/$language/lemmatiser/$foptarg$periodsubdir$dict' -i $filename -o $tmpno";
        else if($Opresfrq ) 
            if($Ofacetlem)
                $command = "$toolbin/cstlemma -L $Iflat -eU -p -qfwt -t$toptarg -U$Uminus -u$Uminus -H$H -B'\$f\\t\$w\\n' -b'\$f\\t\$w\\n' -l- -f'$toolres/$language/lemmatiser/$foptarg$periodsubdir$flexrulessubdir/$flexrules' -d'$toolres/$language/lemmatiser/$foptarg$periodsubdir$dict' -i $filename -o $tmpno";
            else if($ShowTag)
                $command = "$toolbin/cstlemma -L $Iflat -eU -p -qfwt -t$toptarg -U$Uminus -u$Uminus -H$H -B'\$f\\t\$w\\t\$W\\n' -b'\$f\\t\$w\\t\$W\\n' -W'\$f\\t\$w\\t\$t' -l- -f'$toolres/$language/lemmatiser/$foptarg$periodsubdir$flexrulessubdir/$flexrules' -d'$toolres/$language/lemmatiser/$foptarg$periodsubdir$dict' -i $filename -o $tmpno";
            else
                $command = "$toolbin/cstlemma -L $Iflat -eU -p -qfwt -t$toptarg -U$Uminus -u$Uminus -H$H -B'\$f\\t\$w\\t\$W\\n' -b'\$f\\t\$w\\t\$W\\n' -W'\$f\\t\$w' -l- -f'$toolres/$language/lemmatiser/$foptarg$periodsubdir$flexrulessubdir/$flexrules' -d'$toolres/$language/lemmatiser/$foptarg$periodsubdir$dict' -i $filename -o $tmpno";
        else
            $command = "$toolbin/cstlemma -L $Iflat -eU -p -q- -t$toptarg -U$Uminus -u$Uminus -H$H -B'\$w' -b'\$w' -c'$c' -l- -f'$toolres/$language/lemmatiser/$foptarg$periodsubdir$flexrulessubdir/$flexrules' -d'$toolres/$language/lemmatiser/$foptarg$periodsubdir$dict' -i $filename -o $tmpno";
        }
    else if($emptyattribute != "")
        if($posattribute != "")
            $command = "$toolbin/cstlemma -L -Xl$emptyattribute -Xp$posattribute -eU -p -q- -t$toptarg -U$Uminus -u$Uminus -H$H -B'\$w' -b'\$w' -c'$cx' -l- -f'$toolres/$language/lemmatiser/$foptarg$periodsubdir$flexrulessubdir/$flexrules' -d'$toolres/$language/lemmatiser/$foptarg$periodsubdir$dict' -i $filename -o $tmpno";
        else
            $command = "$toolbin/cstlemma -L -Xl$emptyattribute -I'\$w\\s' -eU -p -q- -t$toptarg -U$Uminus -u$Uminus -H$H -B'\$w' -b'\$w' -c'$cx' -l- -f'$toolres/$language/lemmatiser/$foptarg$periodsubdir$flexrulessubdir/$flexrules' -d'$toolres/$language/lemmatiser/$foptarg$periodsubdir$dict' -i $filename -o $tmpno";
    else if($XMLinput == 'j')
        $command = "$toolbin/cstlemma -L -X $Iflat -eU -p -q- -t$toptarg -U$Uminus -u$Uminus -H$H -B'\$w' -b'\$w' -c'$cx' -l- -f'$toolres/$language/lemmatiser/$foptarg$periodsubdir$flexrulessubdir/$flexrules' -d'$toolres/$language/lemmatiser/$foptarg$periodsubdir$dict' -i $filename -o $tmpno";
    else
        $command = "$toolbin/cstlemma -L $Iflat -eU -p -q- -t$toptarg -U$Uminus -u$Uminus -H$H -B'\$w' -b'\$w' -c'$c' -l- -f'$toolres/$language/lemmatiser/$foptarg$periodsubdir$flexrulessubdir/$flexrules' -d'$toolres/$language/lemmatiser/$foptarg$periodsubdir$dict' -i $filename -o $tmpno";

    if($XMLinput == 'j')
        {
        if($pos != 'n')
            {
            $command = $command . " -Xppos";
            }
        if($ancestor != '')
            {
            $command = $command . ' -Xa' . $ancestor;
            }
        if($element != '')
            {
            $command = $command . ' -Xe' . $element;
            }
        }
        
    if($language == 'en')
        if($toptarg == '')
            {
            $command = $command . " -z'$toolres/en/lemmatiser/tags/lemmatags' -v'$toolres/en/lemmatiser/tags/friends'";
            }

    if($x != "")
	$command = $command . " " . $x;

    $command = $command . $sep;
 
    logit($command);
    logit(getcwd());	
    if(($cmd = popen($command, "r")) == NULL)
        {
        throw new SystemExit(); // instead of exit()
        }

    while($read = fgets($cmd))
        {
        }

    pclose($cmd);
    return $tmpno;
    }


    function merge($toolbin,$uploadfile,$uploadfileAnnotation,$mergeattribute,$emptyattribute)
        {
        $posfile = tempFileName("merge");
        $command = "python3 pymerge.py $uploadfile $uploadfileAnnotation $mergeattribute $posfile $emptyattribute";
        
        logit($command);

        if(($cmd = popen($command, "r")) == NULL)
            {
            throw new SystemExit(); // instead of exit()
            }

        while($read = fgets($cmd))
            {
            }
        return $posfile;
        }


    function add($toolbin,$uploadfile,$attribute,$element,$idprefix,$ancestor)
        {
        global $ERROR;
        $posfile = tempFileName("add-" . $attribute . "-attribute");
        if($idprefix == '')
            {
            $command = "python3 pyaddatt.py $uploadfile $posfile $attribute $ancestor $element -";
            }
        else
            {
            $command = "python3 pyaddatt.py $uploadfile $posfile $attribute $ancestor $element id";
            }
        logit($command);
        if(($cmd = popen($command, "r")) == NULL)
            {
            throw new SystemExit(); // instead of exit()
            }

        while($read = fgets($cmd))
            {
            }
        $handle = @fopen("$posfile", "r");
        if ($handle) 
            {
            if(($buffer = fgets($handle, 4096)) !== false) 
                {
                //logit("buffer:[" . $buffer . "]");
                if(strncmp($buffer,"ERROR",5) == 0)
                    {
                    fclose($handle);
                    $ERROR = $buffer;
                    throw new SystemExit(); // instead of exit()
                    }
                }
            fclose($handle);
            }
        return $posfile;
        }

    function do_CSTLem()
        {
        global $dodelete;
        global $tobedeleted;
/***************
* declarations *
***************/

/*
 * TODO Use the variables defined below to configure your tool for the right 
 * input files and the right settings.
 * The input files are local files that your tool can open and close like any
 * other file.
 * If your tool needs to create temporary files, use the tempFileName() 
 * function. It can mark the temporary files for deletion when the webservice
 * is done. (See the global dodelete variable.)
 */
        $base = "";	/* URL from where this web service downloads input. The generated script takes care of that, so you can ignore this variable. */
        $job = "";	/* Only used if this web service returns 201 and POSTs result later. In that case the uploaded file must have the name of the job. */
        $post2 = "";	/* Only used if this web service returns 201 and POSTs result later. In that case the uploaded file must be posted to this URL. */
        $echos = "";	/* List arguments and their actual values. For sanity check of this generated script. All references to this variable can be removed once your web service is working as intended. */
        $F = "";	/* Input (ONLY used if there is exactly ONE input to this workflow step) */
        $IfacetposF = "";	/* Input with type of content PoS-tags (PoS-tags) */
        $IfacettokF = "";	/* Input with type of content tokens (Tokens) */
        $Iambigamb = false;	/* Ambiguity in input is ambiguous (tvetydig) if true */
        $Iambiguna = false;	/* Ambiguity in input is unambiguous (utvetydig) if true */
        $Iappnrm = false;	/* Appearance in input is normalised (normaliseret) if true */
        $Iappunn = false;	/* Appearance in input is unnormalised (ikke-normaliseret) if true */
        $Ifacetpos = false;	/* Type of content in input is PoS-tags (PoS-tags) if true */
        $Ifacetseg = false;	/* Type of content in input is segments (Sætningssegmenter) if true */
        $Ifacettok = false;	/* Type of content in input is tokens (Tokens) if true */
        $Iformatflat = false;	/* Format in input is plain (flad) if true */
        $Iformattxtann = false;	/* Format in input is TEIP5DKCLARIN_ANNOTATION if true */
        $Ilangaf = false;	/* Language in input is Afrikaans (afrikaans) if true */
        $Ilangbg = false;	/* Language in input is Bulgarian (bulgarsk) if true */
        $Ilangcs = false;	/* Language in input is Czech (tjekkisk) if true */
        $Ilangda = false;	/* Language in input is Danish (dansk) if true */
        $Ilangde = false;	/* Language in input is German (tysk) if true */
        $Ilangel = false;	/* Language in input is Greek (græsk) if true */
        $Ilangen = false;	/* Language in input is English (engelsk) if true */
        $Ilanges = false;	/* Language in input is Spanish (spansk) if true */
        $Ilanget = false;	/* Language in input is Estonian (estisk) if true */
        $Ilangfa = false;	/* Language in input is Persian (persisk) if true */
        $Ilangfr = false;	/* Language in input is French (fransk) if true */
        $Ilanghr = false;	/* Language in input is Croatian (kroatisk) if true */
        $Ilanghu = false;	/* Language in input is Hungarian (ungarsk) if true */
        $Ilangis = false;	/* Language in input is Icelandic (islandsk) if true */
        $Ilangit = false;	/* Language in input is Italian (italiensk) if true */
        $Ilangla = false;	/* Language in input is Latin (latin) if true */
        $Ilangmk = false;	/* Language in input is Macedonian (makedonsk) if true */
        $Ilangnl = false;	/* Language in input is Dutch (nederlandsk) if true */
        $Ilangno = false;	/* Language in input is Norwegian (norsk) if true */
        $Ilangpl = false;	/* Language in input is Polish (polsk) if true */
        $Ilangpt = false;	/* Language in input is Portuguese (portugisisk) if true */
        $Ilangro = false;	/* Language in input is Romanian (rumænsk) if true */
        $Ilangru = false;	/* Language in input is Russian (russisk) if true */
        $Ilangsk = false;	/* Language in input is Slovak (slovakisk) if true */
        $Ilangsl = false;	/* Language in input is Slovene (slovensk) if true */
        $Ilangsr = false;	/* Language in input is Serbian (serbisk) if true */
        $Ilangsv = false;	/* Language in input is Swedish (svensk) if true */
        $Ilanguk = false;	/* Language in input is Ukrainian (ukrainsk) if true */
        $Iperiodc13 = false;	/* Historical period in input is medieval (middelalderen) if true */
        $Iperiodc20 = false;	/* Historical period in input is late modern (moderne tid) if true */
        $Iperiodc21 = false;	/* Historical period in input is contemporary (efterkrigstiden) if true */
        $Ipresnml = false;	/* Assemblage in input is normal if true */
        $Oambigamb = false;	/* Ambiguity in output is ambiguous (tvetydig) if true */
        $Oambiguna = false;	/* Ambiguity in output is unambiguous (utvetydig) if true */
        $Oappnrm = false;	/* Appearance in output is normalised (normaliseret) if true */
        $Oappunn = false;	/* Appearance in output is unnormalised (ikke-normaliseret) if true */
        $Ofacetlem = false;	/* Type of content in output is lemmas (Lemma) if true */
        $Ofacetpos = false;	/* Type of content in output is PoS-tags (PoS-tags) if true */
        $Ofacetseg = false;	/* Type of content in output is segments (Sætningssegmenter) if true */
        $Ofacettok = false;	/* Type of content in output is tokens (Tokens) if true */
        $Oformatflat = false;	/* Format in output is plain (flad) if true */
        $Oformattxtann = false;	/* Format in output is TEIP5DKCLARIN_ANNOTATION if true */
        $Olangaf = false;	/* Language in output is Afrikaans (afrikaans) if true */
        $Olangbg = false;	/* Language in output is Bulgarian (bulgarsk) if true */
        $Olangcs = false;	/* Language in output is Czech (tjekkisk) if true */
        $Olangda = false;	/* Language in output is Danish (dansk) if true */
        $Olangde = false;	/* Language in output is German (tysk) if true */
        $Olangel = false;	/* Language in output is Greek (græsk) if true */
        $Olangen = false;	/* Language in output is English (engelsk) if true */
        $Olanges = false;	/* Language in output is Spanish (spansk) if true */
        $Olanget = false;	/* Language in output is Estonian (estisk) if true */
        $Olangfa = false;	/* Language in output is Persian (persisk) if true */
        $Olangfr = false;	/* Language in output is French (fransk) if true */
        $Olanghr = false;	/* Language in output is Croatian (kroatisk) if true */
        $Olanghu = false;	/* Language in output is Hungarian (ungarsk) if true */
        $Olangis = false;	/* Language in output is Icelandic (islandsk) if true */
        $Olangit = false;	/* Language in output is Italian (italiensk) if true */
        $Olangla = false;	/* Language in output is Latin (latin) if true */
        $Olangmk = false;	/* Language in output is Macedonian (makedonsk) if true */
        $Olangnl = false;	/* Language in output is Dutch (nederlandsk) if true */
        $Olangno = false;	/* Language in output is Norwegian (norsk) if true */
        $Olangpl = false;	/* Language in output is Polish (polsk) if true */
        $Olangpt = false;	/* Language in output is Portuguese (portugisisk) if true */
        $Olangro = false;	/* Language in output is Romanian (rumænsk) if true */
        $Olangru = false;	/* Language in output is Russian (russisk) if true */
        $Olangsk = false;	/* Language in output is Slovak (slovakisk) if true */
        $Olangsl = false;	/* Language in output is Slovene (slovensk) if true */
        $Olangsr = false;	/* Language in output is Serbian (serbisk) if true */
        $Olangsv = false;	/* Language in output is Swedish (svensk) if true */
        $Olanguk = false;	/* Language in output is Ukrainian (ukrainsk) if true */
        $Operiodc13 = false;	/* Historical period in output is medieval (middelalderen) if true */
        $Operiodc20 = false;	/* Historical period in output is late modern (moderne tid) if true */
        $Operiodc21 = false;	/* Historical period in output is contemporary (efterkrigstiden) if true */
        $Opresalf = false;	/* Assemblage in output is alphabetic list (alfabetisk liste) if true */
        $Opresfrq = false;	/* Assemblage in output is frequency list (frekvensliste) if true */
        $Opresnml = false;	/* Assemblage in output is normal if true */
        $IfacetposDSL = false;	/* Style of type of content PoS-tags (PoS-tags) in input is DSL-tagset if true */
        $IfacetposPT = false;	/* Style of type of content PoS-tags (PoS-tags) in input is Penn Treebank if true */
        $IfacetposPar = false;	/* Style of type of content PoS-tags (PoS-tags) in input is CST-tagset if true */
        $IfacetposUni = false;	/* Style of type of content PoS-tags (PoS-tags) in input is Universal Part-of-Speech Tagset if true */
        $OfacetposDSL = false;	/* Style of type of content PoS-tags (PoS-tags) in output is DSL-tagset if true */
        $OfacetposPT = false;	/* Style of type of content PoS-tags (PoS-tags) in output is Penn Treebank if true */
        $OfacetposPar = false;	/* Style of type of content PoS-tags (PoS-tags) in output is CST-tagset if true */
        $OfacetposUni = false;	/* Style of type of content PoS-tags (PoS-tags) in output is Universal Part-of-Speech Tagset if true */

        if( hasArgument("base") )
            {
            $base = getArgument("base");
            }
        if( hasArgument("job") )
            {
            $job = getArgument("job");
            }
        if( hasArgument("post2") )
            {
            $post2 = getArgument("post2");
            }
        $echos = "base=$base job=$job post2=$post2 ";

/*********
* input  *
*********/
        if( hasArgument("F") )
            {        
            $F = requestFile("F");
            if($F == '')
                {
                header("HTTP/1.0 404 Input not found (F parameter). ");
                return;
                }
            $echos = $echos . "F=$F ";
            }
        if( hasArgument("IfacetposF") )
            {        
            $IfacetposF = requestFile("IfacetposF");
            if($IfacetposF == '')
                {
                header("HTTP/1.0 404 Input with type of content 'PoS-tags (PoS-tags)' not found (IfacetposF parameter). ");
                return;
                }
            $echos = $echos . "IfacetposF=$IfacetposF ";
            }
        if( hasArgument("IfacettokF") )
            {        
            $IfacettokF = requestFile("IfacettokF");
            if($IfacettokF == '')
                {
                header("HTTP/1.0 404 Input with type of content 'tokens (Tokens)' not found (IfacettokF parameter). ");
                return;
                }
            $echos = $echos . "IfacettokF=$IfacettokF ";
            }

/************************
* input/output features *
************************/
        if( hasArgument("Iambig") )
            {
            $Iambigamb = existsArgumentWithValue("Iambig", "amb");
            $Iambiguna = existsArgumentWithValue("Iambig", "una");
            $echos = $echos . "Iambigamb=$Iambigamb " . "Iambiguna=$Iambiguna ";
            }
        if( hasArgument("Iapp") )
            {
            $Iappnrm = existsArgumentWithValue("Iapp", "nrm");
            $Iappunn = existsArgumentWithValue("Iapp", "unn");
            $echos = $echos . "Iappnrm=$Iappnrm " . "Iappunn=$Iappunn ";
            }
        if( hasArgument("Ifacet") )
            {
            $Ifacetpos = existsArgumentWithValue("Ifacet", "pos");
            $Ifacetseg = existsArgumentWithValue("Ifacet", "seg");
            $Ifacettok = existsArgumentWithValue("Ifacet", "tok");
            $echos = $echos . "Ifacetpos=$Ifacetpos " . "Ifacetseg=$Ifacetseg " . "Ifacettok=$Ifacettok ";
            }
        if( hasArgument("Iformat") )
            {
            $Iformatflat = existsArgumentWithValue("Iformat", "flat");
            $Iformattxtann = existsArgumentWithValue("Iformat", "txtann");
            $echos = $echos . "Iformatflat=$Iformatflat " . "Iformattxtann=$Iformattxtann ";
            }
        if( hasArgument("Ilang") )
            {
            $Ilangaf = existsArgumentWithValue("Ilang", "af");
            $Ilangbg = existsArgumentWithValue("Ilang", "bg");
            $Ilangcs = existsArgumentWithValue("Ilang", "cs");
            $Ilangda = existsArgumentWithValue("Ilang", "da");
            $Ilangde = existsArgumentWithValue("Ilang", "de");
            $Ilangel = existsArgumentWithValue("Ilang", "el");
            $Ilangen = existsArgumentWithValue("Ilang", "en");
            $Ilanges = existsArgumentWithValue("Ilang", "es");
            $Ilanget = existsArgumentWithValue("Ilang", "et");
            $Ilangfa = existsArgumentWithValue("Ilang", "fa");
            $Ilangfr = existsArgumentWithValue("Ilang", "fr");
            $Ilanghr = existsArgumentWithValue("Ilang", "hr");
            $Ilanghu = existsArgumentWithValue("Ilang", "hu");
            $Ilangis = existsArgumentWithValue("Ilang", "is");
            $Ilangit = existsArgumentWithValue("Ilang", "it");
            $Ilangla = existsArgumentWithValue("Ilang", "la");
            $Ilangmk = existsArgumentWithValue("Ilang", "mk");
            $Ilangnl = existsArgumentWithValue("Ilang", "nl");
            $Ilangno = existsArgumentWithValue("Ilang", "no");
            $Ilangpl = existsArgumentWithValue("Ilang", "pl");
            $Ilangpt = existsArgumentWithValue("Ilang", "pt");
            $Ilangro = existsArgumentWithValue("Ilang", "ro");
            $Ilangru = existsArgumentWithValue("Ilang", "ru");
            $Ilangsk = existsArgumentWithValue("Ilang", "sk");
            $Ilangsl = existsArgumentWithValue("Ilang", "sl");
            $Ilangsr = existsArgumentWithValue("Ilang", "sr");
            $Ilangsv = existsArgumentWithValue("Ilang", "sv");
            $Ilanguk = existsArgumentWithValue("Ilang", "uk");
            $echos = $echos . "Ilangaf=$Ilangaf " . "Ilangbg=$Ilangbg " . "Ilangcs=$Ilangcs " . "Ilangda=$Ilangda " . "Ilangde=$Ilangde " . "Ilangel=$Ilangel " . "Ilangen=$Ilangen " . "Ilanges=$Ilanges " . "Ilanget=$Ilanget " . "Ilangfa=$Ilangfa " . "Ilangfr=$Ilangfr " . "Ilanghr=$Ilanghr " . "Ilanghu=$Ilanghu " . "Ilangis=$Ilangis " . "Ilangit=$Ilangit " . "Ilangla=$Ilangla " . "Ilangmk=$Ilangmk " . "Ilangnl=$Ilangnl " . "Ilangno=$Ilangno " . "Ilangpl=$Ilangpl " . "Ilangpt=$Ilangpt " . "Ilangro=$Ilangro " . "Ilangru=$Ilangru " . "Ilangsk=$Ilangsk " . "Ilangsl=$Ilangsl " . "Ilangsr=$Ilangsr " . "Ilangsv=$Ilangsv " . "Ilanguk=$Ilanguk ";
            }
        if( hasArgument("Iperiod") )
            {
            $Iperiodc13 = existsArgumentWithValue("Iperiod", "c13");
            $Iperiodc20 = existsArgumentWithValue("Iperiod", "c20");
            $Iperiodc21 = existsArgumentWithValue("Iperiod", "c21");
            $echos = $echos . "Iperiodc13=$Iperiodc13 " . "Iperiodc20=$Iperiodc20 " . "Iperiodc21=$Iperiodc21 ";
            }
        if( hasArgument("Ipres") )
            {
            $Ipresnml = existsArgumentWithValue("Ipres", "nml");
            $echos = $echos . "Ipresnml=$Ipresnml ";
            }
        if( hasArgument("Oambig") )
            {
            $Oambigamb = existsArgumentWithValue("Oambig", "amb");
            $Oambiguna = existsArgumentWithValue("Oambig", "una");
            $echos = $echos . "Oambigamb=$Oambigamb " . "Oambiguna=$Oambiguna ";
            }
        if( hasArgument("Oapp") )
            {
            $Oappnrm = existsArgumentWithValue("Oapp", "nrm");
            $Oappunn = existsArgumentWithValue("Oapp", "unn");
            $echos = $echos . "Oappnrm=$Oappnrm " . "Oappunn=$Oappunn ";
            }
        if( hasArgument("Ofacet") )
            {
            $Ofacetlem = existsArgumentWithValue("Ofacet", "lem");
            $Ofacetpos = existsArgumentWithValue("Ofacet", "pos");
            $Ofacetseg = existsArgumentWithValue("Ofacet", "seg");
            $Ofacettok = existsArgumentWithValue("Ofacet", "tok");
            $echos = $echos . "Ofacetlem=$Ofacetlem " . "Ofacetpos=$Ofacetpos " . "Ofacetseg=$Ofacetseg " . "Ofacettok=$Ofacettok ";
            }
        if( hasArgument("Oformat") )
            {
            $Oformatflat = existsArgumentWithValue("Oformat", "flat");
            $Oformattxtann = existsArgumentWithValue("Oformat", "txtann");
            $echos = $echos . "Oformatflat=$Oformatflat " . "Oformattxtann=$Oformattxtann ";
            }
        if( hasArgument("Olang") )
            {
            $Olangaf = existsArgumentWithValue("Olang", "af");
            $Olangbg = existsArgumentWithValue("Olang", "bg");
            $Olangcs = existsArgumentWithValue("Olang", "cs");
            $Olangda = existsArgumentWithValue("Olang", "da");
            $Olangde = existsArgumentWithValue("Olang", "de");
            $Olangel = existsArgumentWithValue("Olang", "el");
            $Olangen = existsArgumentWithValue("Olang", "en");
            $Olanges = existsArgumentWithValue("Olang", "es");
            $Olanget = existsArgumentWithValue("Olang", "et");
            $Olangfa = existsArgumentWithValue("Olang", "fa");
            $Olangfr = existsArgumentWithValue("Olang", "fr");
            $Olanghr = existsArgumentWithValue("Olang", "hr");
            $Olanghu = existsArgumentWithValue("Olang", "hu");
            $Olangis = existsArgumentWithValue("Olang", "is");
            $Olangit = existsArgumentWithValue("Olang", "it");
            $Olangla = existsArgumentWithValue("Olang", "la");
            $Olangmk = existsArgumentWithValue("Olang", "mk");
            $Olangnl = existsArgumentWithValue("Olang", "nl");
            $Olangno = existsArgumentWithValue("Olang", "no");
            $Olangpl = existsArgumentWithValue("Olang", "pl");
            $Olangpt = existsArgumentWithValue("Olang", "pt");
            $Olangro = existsArgumentWithValue("Olang", "ro");
            $Olangru = existsArgumentWithValue("Olang", "ru");
            $Olangsk = existsArgumentWithValue("Olang", "sk");
            $Olangsl = existsArgumentWithValue("Olang", "sl");
            $Olangsr = existsArgumentWithValue("Olang", "sr");
            $Olangsv = existsArgumentWithValue("Olang", "sv");
            $Olanguk = existsArgumentWithValue("Olang", "uk");
            $echos = $echos . "Olangaf=$Olangaf " . "Olangbg=$Olangbg " . "Olangcs=$Olangcs " . "Olangda=$Olangda " . "Olangde=$Olangde " . "Olangel=$Olangel " . "Olangen=$Olangen " . "Olanges=$Olanges " . "Olanget=$Olanget " . "Olangfa=$Olangfa " . "Olangfr=$Olangfr " . "Olanghr=$Olanghr " . "Olanghu=$Olanghu " . "Olangis=$Olangis " . "Olangit=$Olangit " . "Olangla=$Olangla " . "Olangmk=$Olangmk " . "Olangnl=$Olangnl " . "Olangno=$Olangno " . "Olangpl=$Olangpl " . "Olangpt=$Olangpt " . "Olangro=$Olangro " . "Olangru=$Olangru " . "Olangsk=$Olangsk " . "Olangsl=$Olangsl " . "Olangsr=$Olangsr " . "Olangsv=$Olangsv " . "Olanguk=$Olanguk ";
            }
        if( hasArgument("Operiod") )
            {
            $Operiodc13 = existsArgumentWithValue("Operiod", "c13");
            $Operiodc20 = existsArgumentWithValue("Operiod", "c20");
            $Operiodc21 = existsArgumentWithValue("Operiod", "c21");
            $echos = $echos . "Operiodc13=$Operiodc13 " . "Operiodc20=$Operiodc20 " . "Operiodc21=$Operiodc21 ";
            }
        if( hasArgument("Opres") )
            {
            $Opresalf = existsArgumentWithValue("Opres", "alf");
            $Opresfrq = existsArgumentWithValue("Opres", "frq");
            $Opresnml = existsArgumentWithValue("Opres", "nml");
            $echos = $echos . "Opresalf=$Opresalf " . "Opresfrq=$Opresfrq " . "Opresnml=$Opresnml ";
            }

/*******************************
* input/output features styles *
*******************************/
        if( hasArgument("Ifacetpos") )
            {
            $IfacetposDSL = existsArgumentWithValue("Ifacetpos", "DSL");
            $IfacetposPT = existsArgumentWithValue("Ifacetpos", "PT");
            $IfacetposPar = existsArgumentWithValue("Ifacetpos", "Par");
            $IfacetposUni = existsArgumentWithValue("Ifacetpos", "Uni");
            $echos = $echos . "IfacetposDSL=$IfacetposDSL " . "IfacetposPT=$IfacetposPT " . "IfacetposPar=$IfacetposPar " . "IfacetposUni=$IfacetposUni ";
            }
        if( hasArgument("Ofacetpos") )
            {
            $OfacetposDSL = existsArgumentWithValue("Ofacetpos", "DSL");
            $OfacetposPT = existsArgumentWithValue("Ofacetpos", "PT");
            $OfacetposPar = existsArgumentWithValue("Ofacetpos", "Par");
            $OfacetposUni = existsArgumentWithValue("Ofacetpos", "Uni");
            $echos = $echos . "OfacetposDSL=$OfacetposDSL " . "OfacetposPT=$OfacetposPT " . "OfacetposPar=$OfacetposPar " . "OfacetposUni=$OfacetposUni ";
            }

/* DUMMY CODE TO SANITY CHECK GENERATED SCRIPT (TODO Remove one of the two solidi from the beginning of this line to activate your own code)
        $CSTLemfile = tempFileName("CSTLem-results");
        $command = "echo $echos >> $CSTLemfile";
        logit($command);

        if(($cmd = popen($command, "r")) == NULL)
            {
            throw new SystemExit(); // instead of exit()
            }

        while($read = fgets($cmd))
            {
            }

        pclose($cmd);
/*/
// YOUR CODE STARTS HERE.
//        TODO your code!
        //logit($echos);
        $toolbin = '../bin';
        $currdir = getcwd();
        $toolres = '../texton-linguistic-resources';

        if(hasArgument("Ilang"))
            {
            $language = getArgument("Ilang");
            }
        else if(hasArgument("Olang"))
            {
            $language = getArgument("Olang");
            }
        else 
            $language = "";

        if(   $language == "" 
          || (  $language != "af" 
             && $language != "bg" 
             && $language != "cs" 
             && $language != "da" 
             && $language != "de" 
             && $language != "el"
         
             && $language != "en" 
             && $language != "es" 
             && $language != "et" 
             && $language != "fa" 
             && $language != "fr" 
         
             && $language != "hu" 
             && $language != "is" 
             && $language != "it" 
             && $language != "mk" 
             && $language != "la"
         
             && $language != "nl" 
             && $language != "no" 
             && $language != "pl"
             && $language != "pt"
             && $language != "ro"
         
             && $language != "ru" 
             && $language != "sk"
             && $language != "sl"
             && $language != "sr"
             && $language != "sv" 
         
             && $language != "uk" 
             )
          )
            $language = "da";

        $ancestor = "spanGrp";
        $element = "span";
        $annotation = "lemma";
        $idprefix = "L";

        logit   ( " currdir=" . $currdir 
                . " toolres=" . $toolres 
                . " toolbin=" . $toolbin 
                . " language=" . $language 
                . " ancestor=" . $ancestor
                . " element=" . $element 
                . " annotation=" . $annotation 
                . " idprefix=" . $idprefix 
                );

        //chdir($toolres);


        //logit("doit($language,$ancestor,$element,$annotation,$idprefix)");
        $filename = '';

        $uploadfile = $F;
        if($uploadfile == "")
            $uploadfile = $IfacettokF;
        if($uploadfile == '')
            {
            header("HTTP/1.0 404 Input tokens not found (F or IfacettokF parameter). ");
            return;
            }

        logit("uploadfile = $uploadfile");

        if($Ifacetpos)
            { // lemmatise with pos input
            logit("Input has tags");
            $ShowTag = $Ofacetpos;
            logit("ShowTag=$ShowTag");
            if($Iformattxtann)
                {
                $uploadfileAnnotation = $IfacetposF;
                $lemmainputfile = merge($toolbin,$uploadfile,$uploadfileAnnotation,'pos','lemma');
                logit("lemmatise with pos in stand off annotation.");
                $CSTLemfile = lemmatiser($Oformatflat,$Ofacetlem,$Ofacetpos,$Ofacetseg,$Ofacettok,$ShowTag, $Ipresnml, $Opresalf,$Opresfrq,$Opresnml, $Oambiguna, $Iappnrm,$element,$ancestor,$toolres,$toolbin,$language,'','tags',$lemmainputfile,'j','pos','lemma','j',$Iperiodc13,$Iperiodc20);
                }
            else
                {
                if($Iformatflat)
                    {
                    logit('lemmatise flat text that has pos tags embedded');
                    $CSTLemfile = lemmatiser($Oformatflat,$Ofacetlem,$Ofacetpos,$Ofacetseg,$Ofacettok,$ShowTag, $Ipresnml, $Opresalf,$Opresfrq,$Opresnml, $Oambiguna, $Iappnrm,$element,$ancestor,$toolres,$toolbin,$language,'','tags',$uploadfile,'j','','','n',$Iperiodc13,$Iperiodc20);
                    }
                else
                    {
                    logit('lemmatise TEI-P5 (not an annotation file)');
                    $CSTLemfile = lemmatiser($Oformatflat,$Ofacetlem,$Ofacetpos,$Ofacetseg,$Ofacettok,$ShowTag, $Ipresnml, $Opresalf,$Opresfrq,$Opresnml, $Oambiguna, $Iappnrm,$element,$ancestor,$toolres,$toolbin,$language,'','tags',$uploadfile,'j','','','j',$Iperiodc13,$Iperiodc20);
                    }
                }
            }
        else
            {
            logit("No tags in input");
            $ShowTag = false;
            if($Iformattxtann)
                {
                logit('add lemma attribute');
                $lemmainputfile = add($toolbin,$uploadfile,'lemma',$element,$idprefix,$ancestor);
                
                logit('lemmatise without pos, stand off tokens');

                $CSTLemfile = lemmatiser($Oformatflat,$Ofacetlem,$Ofacetpos,$Ofacetseg,$Ofacettok,$ShowTag, $Ipresnml, $Opresalf,$Opresfrq,$Opresnml, $Oambiguna, $Iappnrm,$element,$ancestor,$toolres,$toolbin,$language,'-','notags',$lemmainputfile,'n','','lemma','j',$Iperiodc13,$Iperiodc20);
                }
            else
                {
                if($Iformatflat)
                    {
                    logit('lemmatise flat text');
                    $CSTLemfile = lemmatiser($Oformatflat,$Ofacetlem,$Ofacetpos,$Ofacetseg,$Ofacettok,$ShowTag, $Ipresnml, $Opresalf,$Opresfrq,$Opresnml, $Oambiguna, $Iappnrm,$element,$ancestor,$toolres,$toolbin,$language,'-','notags',$uploadfile,'n','','','n',$Iperiodc13,$Iperiodc20);
                    }
                else
                    {
                    logit('lemmatise TEI-P5 (not an annotation file)');
                    $CSTLemfile = lemmatiser($Oformatflat,$Ofacetlem,$Ofacetpos,$Ofacetseg,$Ofacettok,$ShowTag, $Ipresnml, $Opresalf,$Opresfrq,$Opresnml, $Oambiguna, $Iappnrm,$element,$ancestor,$toolres,$toolbin,$language,'-','notags',$uploadfile,'n','','','j',$Iperiodc13,$Iperiodc20);
                    }
                }
            }

        logit("CSTLemfile $CSTLemfile");    
        if($Oformattxtann)
            {
            $CSTLemfile = splits($toolbin,$CSTLemfile,'lemma',$annotation,$idprefix,$ancestor,$element);
            }
            
        //chdir($currdir);
// YOUR CODE ENDS HERE. OUTPUT EXPECTED IN $CSTLemfile
//*/
        $tmpf = fopen($CSTLemfile,'r');

        if($tmpf)
            {
            //logit('output from CSTLem:');
            while($line = fgets($tmpf))
                {
                //logit($line);
                print $line;
                }
            fclose($tmpf);
            }

        if($dodelete)
            {
            foreach ($tobedeleted as $filename => $dot) 
                {
                if($dot)
                    unlink($filename);
                }
            unset($tobedeleted);
            }
        }
    loginit();
    do_CSTLem();
    }
catch (SystemExit $e) 
    { 
    header('HTTP/1.0 404 An error occurred: ' . $ERROR);
    logit('An error occurred' . $ERROR);
    echo $ERROR;
    }
?>

