<?php
header('Content-type:text/plain; charset=UTF-8');
/*
 * This PHP script is generated by CLARIN-DK's tool registration form
 * (http://localhost/texton/register). It should, with no or few adaptations
 * work out of the box as a dummy for your web service. The output returned
 * to the Text Tonsorium (CLARIN-DK's workflow manager) is just a listing of
 * the HTTP parameters received by this web service from the Text Tonsorium,
 * and not the output proper. For that you have to add your code to this script
 * and deactivate the dummy functionality. (The comments near the end of this
 * script explain how that is done.)
 *
 * Places in this script that require your attention are marked 'TODO'.
 */
/*
ToolID         : conll2pt
PassWord       :
Version        : 1.0
Title          : CONLL to Penn Treebank
Path in URL    : /conll2pt	*** TODO make sure your web service listens on this path and that this script is readable for the webserver. ***
Publisher      : CST
ContentProvider: CST
Creator        : Bart Jongejan
InfoAbout      : -
Description    : Convert syntax dependency annotation in CoNLL 2009 or CoNLL-U format to bracketed "Lisp-like" format.
ExternalURI    :
XMLparms       :
PostData       :
Inactive       :
*/

/*******************
* helper functions *
*******************/
$toollog = '../log/conll2pt.log'; /* Used by the logit() function. TODO make sure the folder exists and is writable. Adapt if needed */

/*  TODO Set $dodelete to false if temporary files in /tmp should not be deleted before returning. */
$dodelete = true;
$tobedeleted = array();


function loginit()  /* Wipes the contents of the log file! TODO Change this behaviour if needed. */
    {
    return;
    global $toollog,$ftemp;
    $ftemp = fopen($toollog,'w');
    if($ftemp)
        {
        fwrite($ftemp,$toollog . "\n");
        fclose($ftemp);
        }
    }

function logit($str) /* TODO You can use this function to write strings to the log file. */
    {
    return;
    global $toollog,$ftemp;
    $ftemp = fopen($toollog,'a');
    if($ftemp)
        {
        fwrite($ftemp,$str . "\n");
        fclose($ftemp);
        }
    }

function scripinit($inputF,$input,$output)  /* Initialises outputfile. */
    {
    global $fscrip, $conll2ptfile;
    $fscrip = fopen($conll2ptfile,'w');
    if($fscrip)
        {
        fwrite($fscrip,"/*\n");
        fwrite($fscrip," * ToolID           : conll2pt\n");
        fwrite($fscrip," * Version          : 1.0\n");
        fwrite($fscrip," * Title            : CONLL to Penn Treebank\n");
        fwrite($fscrip," * ServiceURL       : http://localhost//conll2pt\n");
        fwrite($fscrip," * Publisher        : CST\n");
        fwrite($fscrip," * ContentProvider  : CST\n");
        fwrite($fscrip," * Creator          : Bart Jongejan\n");
        fwrite($fscrip," * InfoAbout        : -\n");
        fwrite($fscrip," * Description      : Convert syntax dependency annotation in CoNLL 2009 or CoNLL-U format to bracketed \"Lisp-like\" format.\n");
        fwrite($fscrip," * ExternalURI      : \n");
        fwrite($fscrip," * inputF " . $inputF . "\n");
        fwrite($fscrip," * input  " . $input  . "\n");
        fwrite($fscrip," * output " . $output . "\n");
        fwrite($fscrip," */\n");
        fwrite($fscrip,"\ncd " . getcwd() . "\n");
        fclose($fscrip);
        }
    }

function scrip($str) /* TODO send comments and command line instructions. Don't forget to terminate string with new line character, if needed.*/
    {
    global $fscrip, $conll2ptfile;
    $fscrip = fopen($conll2ptfile,'a');
    if($fscrip)
        {
        fwrite($fscrip,$str . "\n");
        fclose($fscrip);
        }
    }

class SystemExit extends Exception {}
try {
    function hasArgument ($parameterName)
        {
        return isset($_REQUEST["$parameterName"]);
        }

    function getArgument ($parameterName)
        {
        return isset($_REQUEST["$parameterName"]) ? $_REQUEST["$parameterName"] : "";
        }

    function existsArgumentWithValue ($parameterName, $parameterValue)
        {
        /* Check whether there is an argument <parameterName> that has value
           <parameterValue>.
           There may be any number of arguments with name <parameterName> !
        */
        $query  = explode('&', $_SERVER['QUERY_STRING']);

        foreach( $query as $param )
            {
            list($name, $value) = explode('=', $param);
            if($parameterName == urldecode($name) && $parameterValue == urldecode($value))
                return true;
            }
        return false;
        }

    function tempFileName($suff) /* TODO Use this to create temporary files, if needed. */
        {
        global $dodelete;
        global $tobedeleted;
        $tmpno = tempnam('/tmp', $suff);
        if($dodelete)
            $tobedeleted[$tmpno] = true;
        return $tmpno;
        }

    function requestFile($requestParm) // e.g. "IfacettokF"
        {
        logit("requestFile({$requestParm})");

        if(isset($_REQUEST[$requestParm]))
            {
            $urlbase = isset($_REQUEST["base"]) ? $_REQUEST["base"] : "http://localhost/toolsdata/";

            $item = $_REQUEST[$requestParm];
            $url = $urlbase . urlencode($item);
            logit("requestParm:$requestParm");
            logit("urlbase:$urlbase");
            logit("item:$item");
            logit("url[$url]");

            $handle = fopen($url, "r");
            if($handle == false)
                {
                logit("Cannot open url[$url]");
                return "";
                }
            else
                {
                $tempfilename = tempFileName("conll2pt_{$requestParm}_");
                $temp_fh = fopen($tempfilename, 'w');
                if($temp_fh == false)
                    {
                    fclose($handle);
                    logit("handle closed. Cannot open $tempfilename");
                    return "";
                    }
                else
                    {
                    while (!feof($handle))
                        {
                        $read = fread($handle, 8192);
                        fwrite($temp_fh, $read);
                        }
                    fclose($temp_fh);
                    fclose($handle);
                    return $tempfilename;
                    }
                }
            }
        logit("empty");
        return "";
        }

    function do_conll2pt()
        {
        global $conll2ptfile;
        global $dodelete;
        global $tobedeleted;
/***************
* declarations *
***************/

/*
 * TODO Use the variables defined below to configure your tool for the right
 * input files and the right settings.
 * The input files are local files that your tool can open and close like any
 * other file.
 * If your tool needs to create temporary files, use the tempFileName()
 * function. It can mark the temporary files for deletion when the webservice
 * is done. (See the global dodelete variable.)
 */
        $base = "";	/* URL from where this web service downloads input. The generated script takes care of that, so you can ignore this variable. */
        $job = "";	/* Only used if this web service returns 201 and POSTs result later. In that case the uploaded file must have the name of the job. */
        $post2 = "";	/* Only used if this web service returns 201 and POSTs result later. In that case the uploaded file must be posted to this URL. */
        $mode = "";	/* If the value is 'dry', the wrapper is expected to return a script of what will be done if the value is not 'dry', but 'run'. */
        $inputF = "";	/* List of all input files. */
        $input = "";	/* List of all input features. */
        $output = "";	/* List of all output features. */
        $echos = "";	/* List arguments and their actual values. For sanity check of this generated script. All references to this variable can be removed once your web service is working as intended. */
        $F = "";	/* Input (ONLY used if there is exactly ONE input to this workflow step) */
        $Ifacet_lem_mrf_ner_pos_seg_stx_tok = false;	/* Type of content in input is lemmas (lemmaer) and morphological features (morfologiske træk) and name entities (navne) and PoS-tags (PoS-tags) and segments (sætningssegmenter) and syntax (dependency structure) (syntaks (dependensstruktur)) and tokens (tokens) if true */
        $Ifacet_lem_mrf_pos_seg_stx_tok = false;	/* Type of content in input is lemmas (lemmaer) and morphological features (morfologiske træk) and PoS-tags (PoS-tags) and segments (sætningssegmenter) and syntax (dependency structure) (syntaks (dependensstruktur)) and tokens (tokens) if true */
        $Ifacet_lem_pos_seg_stx_tok = false;	/* Type of content in input is lemmas (lemmaer) and PoS-tags (PoS-tags) and segments (sætningssegmenter) and syntax (dependency structure) (syntaks (dependensstruktur)) and tokens (tokens) if true */
        $Ifacet_pos_seg_stx_tok = false;	/* Type of content in input is PoS-tags (PoS-tags) and segments (sætningssegmenter) and syntax (dependency structure) (syntaks (dependensstruktur)) and tokens (tokens) if true */
        $Iformatconll = false;	/* Format in input is CoNLL if true */
        $Ipresnml = false;	/* Assemblage in input is normal if true */
        $Ofacetpos = false;	/* Type of content in output is PoS-tags (PoS-tags) if true */
        $Ofacetseg = false;	/* Type of content in output is segments (sætningssegmenter) if true */
        $Ofacetstx = false;	/* Type of content in output is syntax (dependency structure) (syntaks (dependensstruktur)) if true */
        $Ofacettok = false;	/* Type of content in output is tokens (tokens) if true */
        $Oformatpt = false;	/* Format in output is Penn Treebank if true */
        $Opresnml = false;	/* Assemblage in output is normal if true */
        $IformatconllclU = false;	/* Style of format CoNLL in input is CoNLL-U (10 columns)CoNLL-U (10 kolonner) if true */

        if( hasArgument("base") )
            {
            $base = getArgument("base");
            }
        if( hasArgument("job") )
            {
            $job = getArgument("job");
            }
        if( hasArgument("post2") )
            {
            $post2 = getArgument("post2");
            }
        if( hasArgument("mode") )
            {
            $mode = getArgument("mode");
            }
        $echos = "base=$base job=$job post2=$post2 mode=$mode ";

/*********
* input  *
*********/
        if( hasArgument("F") )
            {
            $F = requestFile("F");
            if($F == '')
                {
                header("HTTP/1.0 404 Input not found (F parameter). ");
                return;
                }
            $echos = $echos . "F=$F ";
            $inputF = $inputF . " \$F ";
            }

/************************
* input/output features *
************************/
        if( hasArgument("Ifacet") )
            {
            $Ifacet_lem_mrf_ner_pos_seg_stx_tok = existsArgumentWithValue("Ifacet", "_lem_mrf_ner_pos_seg_stx_tok");
            $Ifacet_lem_mrf_pos_seg_stx_tok = existsArgumentWithValue("Ifacet", "_lem_mrf_pos_seg_stx_tok");
            $Ifacet_lem_pos_seg_stx_tok = existsArgumentWithValue("Ifacet", "_lem_pos_seg_stx_tok");
            $Ifacet_pos_seg_stx_tok = existsArgumentWithValue("Ifacet", "_pos_seg_stx_tok");
            $echos = $echos . "Ifacet_lem_mrf_ner_pos_seg_stx_tok=$Ifacet_lem_mrf_ner_pos_seg_stx_tok " . "Ifacet_lem_mrf_pos_seg_stx_tok=$Ifacet_lem_mrf_pos_seg_stx_tok " . "Ifacet_lem_pos_seg_stx_tok=$Ifacet_lem_pos_seg_stx_tok " . "Ifacet_pos_seg_stx_tok=$Ifacet_pos_seg_stx_tok ";
            $input = $input . ($Ifacet_lem_mrf_ner_pos_seg_stx_tok ? " \$Ifacet_lem_mrf_ner_pos_seg_stx_tok" : "")  . ($Ifacet_lem_mrf_pos_seg_stx_tok ? " \$Ifacet_lem_mrf_pos_seg_stx_tok" : "")  . ($Ifacet_lem_pos_seg_stx_tok ? " \$Ifacet_lem_pos_seg_stx_tok" : "")  . ($Ifacet_pos_seg_stx_tok ? " \$Ifacet_pos_seg_stx_tok" : "") ;
            }
        if( hasArgument("Iformat") )
            {
            $Iformatconll = existsArgumentWithValue("Iformat", "conll");
            $echos = $echos . "Iformatconll=$Iformatconll ";
            $input = $input . ($Iformatconll ? " \$Iformatconll" : "") ;
            }
        if( hasArgument("Ipres") )
            {
            $Ipresnml = existsArgumentWithValue("Ipres", "nml");
            $echos = $echos . "Ipresnml=$Ipresnml ";
            $input = $input . ($Ipresnml ? " \$Ipresnml" : "") ;
            }
        if( hasArgument("Ofacet") )
            {
            $Ofacetpos = existsArgumentWithValue("Ofacet", "pos");
            $Ofacetseg = existsArgumentWithValue("Ofacet", "seg");
            $Ofacetstx = existsArgumentWithValue("Ofacet", "stx");
            $Ofacettok = existsArgumentWithValue("Ofacet", "tok");
            $echos = $echos . "Ofacetpos=$Ofacetpos " . "Ofacetseg=$Ofacetseg " . "Ofacetstx=$Ofacetstx " . "Ofacettok=$Ofacettok ";
            $output = $output . ($Ofacetpos ? " \$Ofacetpos" : "")  . ($Ofacetseg ? " \$Ofacetseg" : "")  . ($Ofacetstx ? " \$Ofacetstx" : "")  . ($Ofacettok ? " \$Ofacettok" : "") ;
            }
        if( hasArgument("Oformat") )
            {
            $Oformatpt = existsArgumentWithValue("Oformat", "pt");
            $echos = $echos . "Oformatpt=$Oformatpt ";
            $output = $output . ($Oformatpt ? " \$Oformatpt" : "") ;
            }
        if( hasArgument("Opres") )
            {
            $Opresnml = existsArgumentWithValue("Opres", "nml");
            $echos = $echos . "Opresnml=$Opresnml ";
            $output = $output . ($Opresnml ? " \$Opresnml" : "") ;
            }

/*******************************
* input/output features styles *
*******************************/
        if( hasArgument("Iformatconll") )
            {
            $IformatconllclU = existsArgumentWithValue("Iformatconll", "clU");
            $echos = $echos . "IformatconllclU=$IformatconllclU ";
            $input = $input . ($IformatconllclU ? " \$IformatconllclU" : "") ;
            }

/* DUMMY CODE TO SANITY CHECK GENERATED SCRIPT (TODO Remove one of the two solidi from the beginning of this line to activate your own code)
        $conll2ptfile = tempFileName("conll2pt-results");
        $command = "echo $echos >> $conll2ptfile";
        logit($command);

        if(($cmd = popen($command, "r")) == NULL)
            {
            throw new SystemExit(); // instead of exit()
            }

        while($read = fgets($cmd))
            {
            }

        pclose($cmd);
/*/
// YOUR CODE STARTS HERE.
//        TODO your code!
        $conll2ptfile = tempFileName("conll2pt-results");
        if($mode == 'dry')
        {
            scripinit($inputF,$input,$output);
            scrip("../bin/bracmat 'get\$\"conll2pt.bra\"' '\$F' '\$conll2ptfile'");
        }
        else
        {
            $command = "../bin/bracmat 'get\$\"conll2pt.bra\"' '$F' '$conll2ptfile'";

            logit($command);

            if(($cmd = popen($command, "r")) == NULL)
            {
                throw new SystemExit(); // instead of exit()
            }

            while($read = fgets($cmd))
            {
            }

            pclose($cmd);
        }
// YOUR CODE ENDS HERE. OUTPUT EXPECTED IN $conll2ptfile
//*/
        $tmpf = fopen($conll2ptfile,'r');

        if($tmpf)
            {
            //logit('output from conll2pt:');
            while($line = fgets($tmpf))
                {
                //logit($line);
                print $line;
                }
            fclose($tmpf);
            }

        if($dodelete)
            {
            foreach ($tobedeleted as $filename => $dot)
                {
                if($dot)
                    unlink($filename);
                }
            unset($tobedeleted);
            }
        }
    loginit();
    do_conll2pt();
    }
catch (SystemExit $e)
    {
    header('HTTP/1.0 404 An error occurred: ' . $ERROR);
    logit('An error occurred' . $ERROR);
    echo $ERROR;
    }
?>

