<?php
header("Content-type:text/plain; charset=UTF-8");
/*
 * This PHP script is generated by CLARIN-DK's tool registration form 
 * (https://clarin.dk/tools/register). It should, with no or few adaptations
 * work out of the box as a dummy for your web service. The output returned
 * to the CLARIN-DK workflow manager is just a listing of the HTTP parameters
 * received by this web service from the CLARIN-DK workflow manager, and not
 * the output proper. For that you have to add your code to this script and
 * deactivate the dummy functionality. (The comments near the end of this
 * script explain how that is done.)
 *
 * Places in this script that require your attention are marked 'TODO'.
 */
/*
ToolID         : orgconv
PassWord       : 
Version        : 1.0
Title          : Orgmode converter
ServiceURL     : http://localhost/orgconv	*** TODO make sure your web service listens on this address and that this script is readable for the webserver. ***
Publisher      : CST
ContentProvider: CST
Creator        : Bart Jongejan
InfoAbout      : -
Description    : Store lemma in column 3 and/or word class in column 4 of an orgmode input file that already has diplomatic and facsimal values in columns 7 and 8.
ExternalURI    : 
XMLparms       : 
PostData       : 
Inactive       : 
*/

/*******************
* helper functions *
*******************/
$toollog = '../log/orgconv.log'; /* Used by the logit() function. TODO make sure the folder exists and is writable. Adapt if needed */
                
/*  TODO Set $dodelete to false if temporary files in /tmp should not be deleted before returning. */
$dodelete = true;
$tobedeleted = array();


function loginit()  /* Wipes the contents of the log file! TODO Change this behaviour if needed. */
    {
    global $toollog,$ftemp;
    $ftemp = fopen($toollog,'w');
    if($ftemp)
        {
        fwrite($ftemp,$toollog . "\n");
        fclose($ftemp);
        }
    }
    
function logit($str) /* TODO You can use this function to write strings to the log file. */
    {
    global $toollog,$ftemp;
    $ftemp = fopen($toollog,'a');
    if($ftemp)
        {
        fwrite($ftemp,$str . "\n");
        fclose($ftemp);
        }
    }
    
class SystemExit extends Exception {}
try {
    function hasArgument ($parameterName)
        {
        return isset($_REQUEST["$parameterName"]);
        }

    function getArgument ($parameterName)
        {
        return isset($_REQUEST["$parameterName"]) ? $_REQUEST["$parameterName"] : "";
        }

    function existsArgumentWithValue ($parameterName, $parameterValue)
        {
        /* Check whether there is an argument <parameterName> that has value 
           <parameterValue>. 
           There may be any number of arguments with name <parameterName> !
        */
        $query  = explode('&', $_SERVER['QUERY_STRING']);

        foreach( $query as $param )
            {
            list($name, $value) = explode('=', $param);
            if($parameterName == urldecode($name) && $parameterValue == urldecode($value))
                return true;
            }
        return false;
        }

    function tempFileName($suff) /* TODO Use this to create temporary files, if needed. */
        {
        global $dodelete;
        global $tobedeleted;
        $tmpno = tempnam('/tmp', $suff);
        if($dodelete)
            $tobedeleted[$tmpno] = true;
        return $tmpno;
        }
        
    function requestFile($requestParm) // e.g. "IfacettokF"
        {
        //logit("requestFile(" . $requestParm . ")");

        if(isset($_REQUEST[$requestParm]))
            {
            $urlbase = isset($_REQUEST["base"]) ? $_REQUEST["base"] : "http://localhost/toolsdata/";

            $item = $_REQUEST[$requestParm];
            $url = $urlbase . $item;
            /*logit("requestParm:$requestParm");
            logit("urlbase:$urlbase");
            logit("item:$item");
            logit("url[$url]");*/

            $handle = fopen($url, "r");
            if($handle == false)
                {
                //logit("Cannot open url[$url]");
                return "";
                }
            else
                {
                $tempfilename = tempFileName("orgconv_$requestParm_");
                $temp_fh = fopen($tempfilename, 'w');
                if($temp_fh == false)
                    {
                    fclose($handle);
                    //logit("handle closed. Cannot open $tempfilename");
                    return "";
                    }
                else
                    {
                    while (!feof($handle)) 
                        {
                        $read = fread($handle, 8192);
                        fwrite($temp_fh, $read);    
                        }
                    fclose($temp_fh);
                    fclose($handle);
                    return $tempfilename;
                    }
                }
            }
        //logit("empty");
        return "";
        }    

    function do_orgconv()
        {
        global $dodelete;
        global $tobedeleted;
/***************
* declarations *
***************/

/*
 * TODO Use the variables defined below to configure your tool for the right 
 * input files and the right settings.
 * The input files are local files that your tool can open and close like any
 * other file.
 * If your tool needs to create temporary files, use the tempFileName() 
 * function. It can mark the temporary files for deletion when the webservice
 * is done. (See the global dodelete variable.)
 */
        $base = "";	/* URL from where this web service downloads input. The generated script takes care of that, so you can ignore this variable. */
        $job = "";	/* Only used if this web service returns 201 and POSTs result later. In that case the uploaded file must have the name of the job. */
        $post2 = "";	/* Only used if this web service returns 201 and POSTs result later. In that case the uploaded file must be posted to this URL. */
        $echos = "";	/* List arguments and their actual values. For sanity check of this generated script. All references to this variable can be removed once your web service is working as intended. */
        $IfacettlF = "";	/* Input with type of content tokens,lemmas (tokens,lemmaer) */
        $IfacettlpF = "";	/* Input with type of content tokens,PoS-tags,lemmas (tokens,PoS-tags,lemmaer) */
        $IfacettokF = "";	/* Input with type of content tokens (Tokens) */
        $IfacettpF = "";	/* Input with type of content tokens,PoS-tags (tokens,PoS-tags) */
        $Iambiguna = false;	/* Ambiguity in input is unambiguous (utvetydig) if true */
        $Iappnrm = false;	/* Appearance in input is normalised (normaliseret) if true */
        $Iappunn = false;	/* Appearance in input is unnormalised (ikke-normaliseret) if true */
        $Ifacettl = false;	/* Type of content in input is tokens,lemmas (tokens,lemmaer) if true */
        $Ifacettlp = false;	/* Type of content in input is tokens,PoS-tags,lemmas (tokens,PoS-tags,lemmaer) if true */
        $Ifacettok = false;	/* Type of content in input is tokens (Tokens) if true */
        $Ifacettp = false;	/* Type of content in input is tokens,PoS-tags (tokens,PoS-tags) if true */
        $Iformatdipl = false;	/* Format in input is Org-mode if true */
        $Ipresnml = false;	/* Presentation in input is normal if true */
        $Oambiguna = false;	/* Ambiguity in output is unambiguous (utvetydig) if true */
        $Oappnrm = false;	/* Appearance in output is normalised (normaliseret) if true */
        $Oappunn = false;	/* Appearance in output is unnormalised (ikke-normaliseret) if true */
        $Ofacettlp = false;	/* Type of content in output is tokens,PoS-tags,lemmas (tokens,PoS-tags,lemmaer) if true */
        $Oformatdipl = false;	/* Format in output is Org-mode if true */
        $Opresnml = false;	/* Presentation in output is normal if true */
        $IfacettlpMenotas = false;	/* Style of type of content tokens,PoS-tags,lemmas (tokens,PoS-tags,lemmaer) in input is (Penn Treebank.PT.)(CST-tagset.Par.)(Parole-Moses.ParMos.)(DSL-tagset.DSL.)(CST new tag setCST_nyt_tagsæt.CSTnyt.)(Universal Part-of-Speech Tagset.Uni.)(Menotas.Menotas.) if true */
        $IfacettpMenotas = false;	/* Style of type of content tokens,PoS-tags (tokens,PoS-tags) in input is (Penn Treebank.PT.)(CST-tagset.Par.)(Parole-Moses.ParMos.)(DSL-tagset.DSL.)(CST new tag setCST_nyt_tagsæt.CSTnyt.)(Universal Part-of-Speech Tagset.Uni.)(Menotas.Menotas.) if true */
        $OfacettlpMenotas = false;	/* Style of type of content tokens,PoS-tags,lemmas (tokens,PoS-tags,lemmaer) in output is (Penn Treebank.PT.)(CST-tagset.Par.)(Parole-Moses.ParMos.)(DSL-tagset.DSL.)(CST new tag setCST_nyt_tagsæt.CSTnyt.)(Universal Part-of-Speech Tagset.Uni.)(Menotas.Menotas.) if true */

        if( hasArgument("base") )
            {
            $base = getArgument("base");
            }
        if( hasArgument("job") )
            {
            $job = getArgument("job");
            }
        if( hasArgument("post2") )
            {
            $post2 = getArgument("post2");
            }
        $echos = "base=$base job=$job post2=$post2 ";

/*********
* input  *
*********/
        if( hasArgument("IfacettlF") )
            {        
            $IfacettlF = requestFile("IfacettlF");
            if($IfacettlF == '')
                {
                header("HTTP/1.0 404 Input with type of content 'tokens,lemmas (tokens,lemmaer)' not found (IfacettlF parameter). ");
                return;
                }
            $echos = $echos . "IfacettlF=$IfacettlF ";
            }
        if( hasArgument("IfacettlpF") )
            {        
            $IfacettlpF = requestFile("IfacettlpF");
            if($IfacettlpF == '')
                {
                header("HTTP/1.0 404 Input with type of content 'tokens,PoS-tags,lemmas (tokens,PoS-tags,lemmaer)' not found (IfacettlpF parameter). ");
                return;
                }
            $echos = $echos . "IfacettlpF=$IfacettlpF ";
            }
        if( hasArgument("IfacettokF") )
            {        
            $IfacettokF = requestFile("IfacettokF");
            if($IfacettokF == '')
                {
                header("HTTP/1.0 404 Input with type of content 'tokens (Tokens)' not found (IfacettokF parameter). ");
                return;
                }
            $echos = $echos . "IfacettokF=$IfacettokF ";
            }
        if( hasArgument("IfacettpF") )
            {        
            $IfacettpF = requestFile("IfacettpF");
            if($IfacettpF == '')
                {
                header("HTTP/1.0 404 Input with type of content 'tokens,PoS-tags (tokens,PoS-tags)' not found (IfacettpF parameter). ");
                return;
                }
            $echos = $echos . "IfacettpF=$IfacettpF ";
            }

/************************
* input/output features *
************************/
        if( hasArgument("Iambig") )
            {
            $Iambiguna = existsArgumentWithValue("Iambig", "una");
            $echos = $echos . "Iambiguna=$Iambiguna ";
            }
        if( hasArgument("Iapp") )
            {
            $Iappnrm = existsArgumentWithValue("Iapp", "nrm");
            $Iappunn = existsArgumentWithValue("Iapp", "unn");
            $echos = $echos . "Iappnrm=$Iappnrm " . "Iappunn=$Iappunn ";
            }
        if( hasArgument("Ifacet") )
            {
            $Ifacettl = existsArgumentWithValue("Ifacet", "tl");
            $Ifacettlp = existsArgumentWithValue("Ifacet", "tlp");
            $Ifacettok = existsArgumentWithValue("Ifacet", "tok");
            $Ifacettp = existsArgumentWithValue("Ifacet", "tp");
            $echos = $echos . "Ifacettl=$Ifacettl " . "Ifacettlp=$Ifacettlp " . "Ifacettok=$Ifacettok " . "Ifacettp=$Ifacettp ";
            }
        if( hasArgument("Iformat") )
            {
            $Iformatdipl = existsArgumentWithValue("Iformat", "dipl");
            $echos = $echos . "Iformatdipl=$Iformatdipl ";
            }
        if( hasArgument("Ipres") )
            {
            $Ipresnml = existsArgumentWithValue("Ipres", "nml");
            $echos = $echos . "Ipresnml=$Ipresnml ";
            }
        if( hasArgument("Oambig") )
            {
            $Oambiguna = existsArgumentWithValue("Oambig", "una");
            $echos = $echos . "Oambiguna=$Oambiguna ";
            }
        if( hasArgument("Oapp") )
            {
            $Oappnrm = existsArgumentWithValue("Oapp", "nrm");
            $Oappunn = existsArgumentWithValue("Oapp", "unn");
            $echos = $echos . "Oappnrm=$Oappnrm " . "Oappunn=$Oappunn ";
            }
        if( hasArgument("Ofacet") )
            {
            $Ofacettlp = existsArgumentWithValue("Ofacet", "tlp");
            $echos = $echos . "Ofacettlp=$Ofacettlp ";
            }
        if( hasArgument("Oformat") )
            {
            $Oformatdipl = existsArgumentWithValue("Oformat", "dipl");
            $echos = $echos . "Oformatdipl=$Oformatdipl ";
            }
        if( hasArgument("Opres") )
            {
            $Opresnml = existsArgumentWithValue("Opres", "nml");
            $echos = $echos . "Opresnml=$Opresnml ";
            }

/*******************************
* input/output features styles *
*******************************/
        if( hasArgument("Ifacettlp") )
            {
            $IfacettlpMenotas = existsArgumentWithValue("Ifacettlp", "Menotas");
            $echos = $echos . "IfacettlpMenotas=$IfacettlpMenotas ";
            }
        if( hasArgument("Ifacettp") )
            {
            $IfacettpMenotas = existsArgumentWithValue("Ifacettp", "Menotas");
            $echos = $echos . "IfacettpMenotas=$IfacettpMenotas ";
            }
        if( hasArgument("Ofacettlp") )
            {
            $OfacettlpMenotas = existsArgumentWithValue("Ofacettlp", "Menotas");
            $echos = $echos . "OfacettlpMenotas=$OfacettlpMenotas ";
            }

/* DUMMY CODE TO SANITY CHECK GENERATED SCRIPT (TODO Remove one of the two solidi from the beginning of this line to activate your own code)
        $orgconvfile = tempFileName("orgconv-results");
        $command = "echo $echos >> $orgconvfile";
        logit($command);

        if(($cmd = popen($command, "r")) == NULL)
            {
            throw new SystemExit(); // instead of exit()
            }

        while($read = fgets($cmd))
            {
            }

        pclose($cmd);
/*/
// YOUR CODE STARTS HERE.
//        TODO your code!
        $command = "echo $echos >> $orgconvfile";
        //logit($command);

        $orgconvfile = tempFileName("orgconv-results");
        if($Ifacettlp)
            $command = "../bin/bracmat 'get\$\"orgconv.bra\"' '$orgconvfile' '$IfacettokF' '$IfacettlpF' '$IfacettlpF' '$Iappnrm'";
        else
            $command = "../bin/bracmat 'get\$\"orgconv.bra\"' '$orgconvfile' '$IfacettokF' '$IfacettpF' '$IfacettlF' '$Iappnrm'";

        //logit($command);

        if(($cmd = popen($command, "r")) == NULL)
            {
            throw new SystemExit(); // instead of exit()
            }

        while($read = fgets($cmd))
            {
            }

        pclose($cmd);

// YOUR CODE ENDS HERE. OUTPUT EXPECTED IN $orgconvfile
//        TODO your code!
// YOUR CODE ENDS HERE. OUTPUT EXPECTED IN $orgconvfile
//*/
        $tmpf = fopen($orgconvfile,'r');

        if($tmpf)
            {
            //logit('output from orgconv:');
            while($line = fgets($tmpf))
                {
                //logit($line);
                print $line;
                }
            fclose($tmpf);
            }

        if($dodelete)
            {
            foreach ($tobedeleted as $filename => $dot) 
                {
                if($dot)
                    unlink($filename);
                }
            unset($tobedeleted);
            }
        }
    //loginit();
    do_orgconv();
    }
catch (SystemExit $e) 
    { 
    header ('An error occurred.' . $ERROR, true , 404 );
    //logit('An error occurred' . $ERROR);
    echo $ERROR;
    }

?>

